package bean;
// Generated 15/09/2025 10:21:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,catalog="db_marcos_vilhanueva"
)
public class Vendedor  implements java.io.Serializable {


     private int idvendedor;
     private String nome;
     private Double salario;
     private Double comissao;
     private String vendedorcol;
     private Set pedidoses = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(int idvendedor) {
        this.idvendedor = idvendedor;
    }
    public Vendedor(int idvendedor, String nome, Double salario, Double comissao, String vendedorcol) {
       this.idvendedor = idvendedor;
       this.nome = nome;
       this.salario = salario;
       this.comissao = comissao;
       this.vendedorcol = vendedorcol;
       this.pedidoses = pedidoses;
    }
   
     @Id 

    
    @Column(name="idvendedor", unique=true, nullable=false)
    public int getIdvendedor() {
        return this.idvendedor;
    }
    
    public void setIdvendedor(int idvendedor) {
        this.idvendedor = idvendedor;
    }

    
    @Column(name="nome", length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="salario", precision=10)
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }

    
    @Column(name="comissao", precision=10)
    public Double getComissao() {
        return this.comissao;
    }
    
    public void setComissao(Double comissao) {
        this.comissao = comissao;
    }

    
    @Column(name="vendedorcol", length=45)
    public String getVendedorcol() {
        return this.vendedorcol;
    }
    
    public void setVendedorcol(String vendedorcol) {
        this.vendedorcol = vendedorcol;
    }

}


